### ISSUE TITLE
Install Algolia package

### ISSUE THREAD

**Issue by codecakes** [Xcov19/covidX#28]
- [Install algolia for django](https://www.algolia.com/doc/framework-integration/django/setup/?language=python)
- Add to requirements

**Comment by myiwt** [comment]
Hi, is is possible for me to work on this?

**Comment by codecakes** [comment]
> Hi, is is possible for me to work on this?

@myiwt please do

**Comment by codecakes** [comment]
@myiwt there're some data pipelilne work i can assign you as well

**Comment by codecakes** [comment]
@myiwt see #29

**Comment by myiwt** [comment]
No troubles at all :) if it's an easier issue I'm happy to take it on since I'm a beginner, otherwise I can help out another time in future

**Comment by codecakes** [comment]
> No troubles at all :) if it's an easier issue I'm happy to take it on since I'm a beginner, otherwise I can help out another time in future

@myiwt its a closed pr for the same issue as this one. you can review it for reference and send a new pr

**Comment by ShubhamNagure** [comment]
Hi,
Can I help you here?

**Comment by iSpy-u** [comment]
Hi, 
What do you need on this issue?

**Comment by premalrupnur** [comment]
Hi would like to take up this issue??

**Comment by codecakes** [comment]
Pls make the changes as per https://github.com/Xcov19/covidX/pull/29 and send a new PR mentioned this issue.
thanks

**Comment by premalrupnur** [comment]
sorry previously I had not adressed a right issue so closed earlier pr , and created  a new
