### ISSUE TITLE
Auth0 callback uri does not include localhost over http

### ISSUE THREAD

**Issue by ElijahAhianyo** [Xcov19/covidX#62]
## How issue was replicated:
- Fired up server on port 8090
- opened the auth0 login [https://dev-mavl72j2.eu.auth0.com/login?client=nvVF8g8x0prPX1kCsC43nXvkdAUpqcjD](https://dev-mavl72j2.eu.auth0.com/login?client=nvVF8g8x0prPX1kCsC43nXvkdAUpqcjD)
- followed sign up prompt which resulted in the error below:

![Screenshot from 2020-12-01 07-34-13](https://user-images.githubusercontent.com/19895635/100753907-4ea51800-33e2-11eb-9f6a-8bda82dcb78a.png)
![Screenshot from 2020-11-30 21-53-24](https://user-images.githubusercontent.com/19895635/100753944-5a90da00-33e2-11eb-8720-4337b2d5b5b0.png)
from the above screenshots the callback uri allowed in the auth0 application settings is `https://localhost:8090/auth0/complete/auth0` hence the error above.

## suggested solution
`http://localhost:8090/auth0/complete/auth0` should be added to the allowed callback URIs

**Comment by codecakes** [comment]
@ElijahAhianyo 
1. can you verify on your own auth0 dummy client app by replacing our env credentials with yours that you are able to access `http://localhost:8090/auth0/complete/auth0` with your suggested resolve?
2. Have you tried running it on 8000?

**Comment by codecakes** [comment]
On my local In PR #63 I run it like:

```bash
BAZEL_USE_CPP_ONLY_TOOLCHAIN=1 DEBUG_ENV=1 SECRET_KEY=dskaj343 CPPFLAGS="$(pg_config --cppflags)" LDFLAGS="$(pg_config --ldflags)" bazel run --spawn_strategy=standalone --copt --aspects=@bazel_tools//tools/python:srcs_version.bzl%find_requirements --verbose_failures=true --show_timestamps=true --python_version=PY3 --build_python_zip --sandbox_debug --color=yes --curses=yes --jobs=2000 --loading_phase_threads=HOST_CPUS --watchfs --action_env=LDFLAGS --action_env=CPPFLAGS --action_env=DEBUG_ENV --action_env=SECRET_KEY :manage -- runserver_plus --cert /tmp/cert localhost:8090
```
