### ISSUE TITLE
Dockerized version cannot connect to postgres db (local setup)

### ISSUE THREAD

**Issue by marcelloromani** [Xcov19/covidX#77]
**Describe the bug**

After following the `Readme` on how to run a local dockerized version of the app, I got the following error:

```
Error occurred during checks: OperationalError('could not connect to server: Connection refused\n\tIs the 
server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\n')
```

**To Reproduce**

* Install and start postgresql on laptop
* Start the app by using the `docker run` command detailed in the `Readme`:
```
docker run --rm -it -e SECRET_KEY=<YOUR_DJANGO_SECRET_KEY> -e DEBUG_ENV=1 -e CPPFLAGS="$(pg_config --cppflags)" -e LDFLAGS="$(pg_config --ldflags)" -e SECRET_ID="SECRET_KEY" -e BUCKET_NAME="gae-bizlead" -e DJANGO_SETTINGS_MODULE="covidX.settings" -e WSGI_APPLICATION="covidX.wsgi.application" --security-opt apparmor=unconfined codecakes/covidx_manage:bazel runserver_plus
```

**Expected behavior**

The app should connect to the postgresql database

The problem is not so much a bug in the application but rather a lack of documentation of the steps required to make the dockerized application talk to the postgresql server running on the local machine.

*NOTE* I think a mucn cleaner solution would be to provide a `docker-compose.yaml` file that also instantiates a `postgresql` server.

**Comment by marcelloromani** [comment]
@premalrupnur here's a rough description of the problem:

- postgresql must be configured to accept connection on TCP port 5432, password authentication must be enabled, the user `postgres` must be assigned the password `postgres` (to match the app's default database configuration)
- the `docker run` command must be changed so that the docker app can connect to port 5432 on the laptop's IP address (if I remember it's `--network bridge` but I need to verify this)

In addition, `-p 8000:8000` needs to be added to the `docker run` command otherwise you can't connect to the django app

**Comment by premalrupnur** [comment]
@marcelloromani were you able to run locally then

**Comment by premalrupnur** [comment]
when I run docker-compose up 
I'm continuously getting this message:
`django-api  |  docker-compose-wait 2.7.3
django-api  | ---------------------------
django-api  | Starting with configuration:
django-api  |  - Hosts to be waiting for: [postgres:5432,redis:6379]
django-api  |  - Timeout before failure: 300 seconds
django-api  |  - TCP connection timeout before retry: 30 seconds
django-api  |  - Sleeping time before checking for hosts availability: 0 seconds
django-api  |  - Sleeping time once all hosts are available: 0 seconds
django-api  |  - Sleeping time between retries: 30 seconds
django-api  | --------------------------------------------------------
django-api  | Checking availability of postgres:5432
django-api  | Host postgres:5432 is now available!
django-api  | --------------------------------------------------------
django-api  | Checking availability of redis:6379
django-api  | Host redis:6379 is now available!
django-api  | --------------------------------------------------------
django-api  | docker-compose-wait - Everything's fine, the application can now start!
django-api  | --------------------------------------------------------
django-api  | sh: 1: /pre-start.sh: not found`

**Comment by codecakes** [comment]
#76 fixes and closes this issue

**Comment by marcelloromani** [comment]
@premalrupnur Yes I managed to connect the docker instance to the local postgresql server that I had installed on my Mac, but that required configuring Postgres and modifying the `docker run` command. I didn't document this process thoroughly because I then switched to the cleaner `docker-compose` method.
