### ISSUE TITLE
Can't start docker-compose: missing .env file

### ISSUE THREAD

**Issue by marcelloromani** [Xcov19/covidX#78]
**Describe the bug**

`docker-compose up` fails with the following error:

```
$ docker-compose up
ERROR: Couldn't find env file: /Users/marcelloromani/dev/xcov19/covidX/.env
```

**Comment by milan-tom** [comment]
You need to create a .env file in your local cloned repository. The format can be derived from the .env_sample file in master repository.

**Comment by milan-tom** [comment]
Perhaps it would be useful for newcomers for a generic `.env` file to be bundled with the repository.

**Comment by marcelloromani** [comment]
To be fair there is a `.env_sample` in the repository, which should have caught my attention.

I'll try that

**Comment by marcelloromani** [comment]
OK, the sample env needs to be populated with the values obtained from the auth0/algolia steps in the readme, but we need clear instructions:
```
SOCIAL_AUTH_TRAILING_SLASH=False # Remove trailing slash from routes
SOCIAL_AUTH_AUTH0_DOMAIN=yourDomain.com
SOCIAL_AUTH_AUTH0_KEY=yourClientId
SOCIAL_AUTH_AUTH0_SECRET=yourClientSecret
ACCESS_TOKEN_METHOD=POST
JWT_AUDIENCE=https://localhost:8000/
ALGOLIA_API_KEY=yourAdminAPIKey
ALGOLIA_APPLICATION_ID=yourApplicationId
POSTGRES_DB_HOST=yourHost.com
POSTGRES_DB_PORT=yourPort
DJANGO_ALLOWED_HOST=yourAllowedHost
```

**Comment by marcelloromani** [comment]
I'll put an explanation of the values as I understand them so far - to be updated:

For Auth0 values:
* Login to Auth0
* Click on "Applications"
* Click on "Default App"

* `SOCIAL_AUTH_AUTH0_DOMAIN=<Domain>`
*  `SOCIAL_AUTH_AUTH0_KEY=`<Client ID>`
* `SOCIAL_AUTH_AUTH0_SECRET=<Client Secret>`

**Comment by codecakes** [comment]
correct

**Comment by marcelloromani** [comment]
Added `https://localhost:8000/auth0/complete/auth0/` to Auth0 Default Application "Allowed Callback URLs"

**Comment by codecakes** [comment]
THe .env provided should work for you

**Comment by marcelloromani** [comment]
```
ALGOLIA_API_KEY=yourAdminAPIKey
ALGOLIA_APPLICATION_ID=yourApplicationId
```

![Screenshot 2021-01-27 at 12 04 54](https://user-images.githubusercontent.com/7853581/105988820-23fcd600-6098-11eb-829f-82df42fe941d.png)

**Comment by marcelloromani** [comment]
Update:

* I generated the `privateKey` and `certificate`
* I filled in the `.env` file with the values detailed above

After that I was able to successfully `docker-compose up` and start the application.
