### ISSUE TITLE
docker-compose freezing after building successfully

### ISSUE THREAD

**Issue by milan-tom** [Xcov19/covidX#79]
**Describe the bug**
After building successfully, `docker-compose` freezes on the following section:
```
(18:29:37) INFO: Analyzed target //:manage (0 packages loaded, 0 targets configured).
(18:29:37) INFO: Found 1 target...
Target //:manage up-to-date:
  bazel-bin/manage
  bazel-bin/manage.zip
(18:29:37) INFO: Elapsed time: 1.356s, Critical Path: 0.01s
(18:29:37) INFO: 1 process: 1 internal.
(18:29:37) INFO: Build completed successfully, 1 total action
(18:29:37) INFO: Build completed successfully, 1 total action
django-api  | 2021-01-25 18:29:42,488 - Logger - INFO - Starting covidX app
django-api  | 2021-01-25 18:29:42,489 - Logger - INFO - BASE_DIR= /tmp/Bazel.runfiles_zcnxqi2m/runfiles/covidx
django-api  | System check identified some issues:
django-api  |
django-api  | WARNINGS:
django-api  | ?: (urls.W001) Your URL pattern '^apihealth/?$' uses include with a route ending with a '$'. Remove the dollar from the route to avoid problems including URLs.
django-api  | ?: (urls.W001) Your URL pattern '^login-rest-router/?$' uses include with a route ending with a '$'. Remove the dollar from the route to avoid problems including URLs.
django-api  | ?: (urls.W001) Your URL pattern '^rest-auth/?$' uses include with a route ending with a '$'. Remove the dollar from the route to avoid problems including URLs.
django-api  | 2021-01-25 18:29:46,783 - Logger - INFO - Starting covidX app
django-api  | 2021-01-25 18:29:46,783 - Logger - INFO - BASE_DIR= /tmp/Bazel.runfiles_zcnxqi2m/runfiles/covidx
django-api  | System check identified some issues:
django-api  |
django-api  | WARNINGS:
django-api  | ?: (urls.W001) Your URL pattern '^apihealth/?$' uses include with a route ending with a '$'. Remove the dollar from the route to avoid problems including URLs.
django-api  | ?: (urls.W001) Your URL pattern '^login-rest-router/?$' uses include with a route ending with a '$'. Remove the dollar from the route to avoid problems including URLs.
django-api  | ?: (urls.W001) Your URL pattern '^rest-auth/?$' uses include with a route ending with a '$'. Remove the dollar from the route to avoid problems including URLs.
django-api  |
django-api  | System check identified 3 issues (0 silenced).

```

**To Reproduce**
1. Clone the repository
2. Add a `.env` file in the cloned repository.
3. Run `docker-compose up --build` 
4. Wait for building to complete
5. See error

**Expected behavior**
Build completed successfully and command terminates

**Screenshots**
The build process freezes upon reaching this section:
![image](https://user-images.githubusercontent.com/48379919/105747877-40cec780-5f39-11eb-939f-50e1eb270383.png)

**Desktop:**
 - OS: Windows 10

**Comment by marcelloromani** [comment]
What are the contents of you `.env` file? In my case I kept the contents of `.env_template` and the `docker-compose up` command built the images and stopped with a reasonable error:
```
$ docker-compose up
[...]
django-api  | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='yourdomain.com', port=443): Max retries exceeded with url: /.well-known/jwks.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47511ab7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by milan-tom** [comment]
> What are the contents of you `.env` file? In my case I kept the contents of `.env_template` and the `docker-compose up` command built the images and stopped with a reasonable error:
> 
> ```
> $ docker-compose up
> [...]
> django-api  | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='yourdomain.com', port=443): Max retries exceeded with url: /.well-known/jwks.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47511ab7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ```

I think you should move this problem to a different issue.

**Comment by milan-tom** [comment]
> What exact command did you run?

`docker-compose up --build`
I have updated the issue comment.

**Comment by marcelloromani** [comment]
I didn't mean to report that issue, I was just saying in my case `docker-compose up` didn't hang like in your case but completed successfully and got to the point where a different (and expected) error showed up.

**Comment by codecakes** [comment]
> What are the contents of you `.env` file? In my case I kept the contents of `.env_template` and the `docker-compose up` command built the images and stopped with a reasonable error:
> 
> ```
> $ docker-compose up
> [...]
> django-api  | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='yourdomain.com', port=443): Max retries exceeded with url: /.well-known/jwks.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f47511ab7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ```
> 
> > Wait for building to complete
> 

This is auth0 related. Solution is straight forward, to allow the domain.

> What exact command did you run?
> 
> I am on Mac OS Big Sur 11.1 and the 'build' command completed successfully (or so it seems):
> 
> ```
> $ docker-compose build
> [...]
> [Warning] One or more build-args [WAIT_HOSTS WAIT_HOSTS_TIMEOUT WAIT_SLEEP_INTERVAL WAIT_HOST_CONNECT_TIMEOUT IS_WAIT] were not consumed
> Successfully built da0a6b3f6780
> Successfully tagged covidx_backend:latest
> ```

This isn't the cause.

**Comment by codecakes** [comment]
One of the causes of this issue is because browser exhausts its ssh  key handshake for self signed keys

**Comment by milan-tom** [comment]
My build is still hanging at the same point even after the merging of pr #76.

**Comment by codecakes** [comment]
you are getting this after merging master?

**Comment by milan-tom** [comment]
> you are getting this after merging master?

Unfortunately, yes @codecakes.

**Comment by milan-tom** [comment]
This seems to be a Windows-specific issue as it is also faced by @premalrupnur.

**Comment by milan-tom** [comment]
`docker-compose` is not actually freezing. The local sever will be visible at `https://localhost:8000` as will be described in the documentation once #82 is merged.
