### ISSUE TITLE
django-api  | sh: 1: /pre-start.sh: not found infinite loop when building with docker-compose

### ISSUE THREAD

**Issue by milan-tom** [Xcov19/covidX#80]
**Describe the bug**
During building using `docker-compose up --build`, an infinte loop is caused with the following message being outputted repeatedly:

```
django-api  | docker-compose-wait - Everything's fine, the application can now start!
django-api  | --------------------------------------------------------
django-api  | sh: 1: /pre-start.sh: not found
```

**To Reproduce**
1. Clone the repository
2. Add a `.env` file in the cloned repository.
3. Run `docker-compose up --build` 
5. See error

**Expected behavior**
Build completed successfully

**Screenshots**
An infinite loop unfolds:
![image](https://user-images.githubusercontent.com/48379919/105751642-382cc000-5f3e-11eb-84f9-c0e0e0b46bd8.png)

**Desktop:**
 - OS: Windows 10

**Comment by milan-tom** [comment]
This is a Windows-specific issue.

Fix:
Convert the line endings of `pre-start.sh` from Windows line endings to Unix line endings

**Comment by milan-tom** [comment]
Could we perhaps just convert the line endings to Unix line endings for `pre-start.sh` by default in the repository @codecakes? Would that cause any further issues?

**Comment by milan-tom** [comment]
> Could we perhaps just convert the line endings to Unix line endings for `pre-start.sh` by default in the repository @codecakes? Would that cause any further issues?

@codecakes I see that this has been done manually in #76.

**Comment by premalrupnur** [comment]
I'm getting the same issue

**Comment by premalrupnur** [comment]
Thanks for this issue @milan-tom  I too , am facing same issue this would help
