### ISSUE TITLE
Use $(...) notation instead of legacy backticked `...`

### ISSUE THREAD

**Issue by codecakes** [Xcov19/covidX#87]
In the line listed here:
https://github.com/Xcov19/covidX/blob/6169b743e820ec8669619e2d37794160fc3f35c8/Dockerfile#L90
uses legacy backticked statement.

**Describe the solution you'd like**
replace backticked statement with $(..) notation.

**Additional context**
Link your PR to this issue;

**Comment by HaardikBhagtani** [comment]
Can u assign this to me?

**Comment by codecakes** [comment]
> Can u assign this to me?

@HaardikBhagtani pls send a PR; you will be automatically assigned;

**Comment by marcelloromani** [comment]
Apologies, I didn't notice first-timers-only and sent a PR straight away
